### ISSUE TITLE
parsing error invaild JSON object  '[' or '{' expected

### ISSUE THREAD

**Issue by aparcar** [tcatm/alfred-json#11]
```
root@meshrc-gw:/tmp# echo -n "foobar" | alfred -s 80
root@meshrc-gw:/tmp# alfred -r 80
{ "88:57:1e:5d:16:43", "foobar" },
root@meshrc-gw:/tmp# alfred-json -r 80
Warning: invalid JSON object from 88:57:1e:5d:16:43: '[' or '{' expected near 'foobar'
```

**Comment by aparcar** [comment]
@ecsv ping?

**Comment by ecsv** [comment]
pong?

Why I am pinged here (alfred-json is not my imported/exporter)? Why should alfred-json parse the raw data which you've inserted here? This tool seems to operate only on json objects and arrays.

**Comment by aparcar** [comment]
@ecsv completely brain afk, I'm sorry for the inconvenience...
